[package]
name = "document-server"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
axum = "0.8.4"
fs2 = "0.4.3"
mime_guess = "2.0.5"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
tar = "0.4.44"
tokio = { version = "1.47.1", features = ["fs", "macros", "net", "rt-multi-thread"] }
zstd = "0.13.3"

[build-dependencies]
zstd = "0.13.3"

[profile.release]
lto = true
codegen-units = 1
strip = true
